name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci_job:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint check
        run: npm run lint

      - name: Run tests (optional)
        run: npm test || echo "No tests found"

  cd_job:
    needs: ci_job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
